### ISSUE TITLE
Not enough features added

### ISSUE THREAD

**Issue by m-andreev** [karastoyanov/linux-hobby-club#4]
-multiply function would be added to (https://github.com/karastoyanov/linux-hobby-club/blob/development/CPP/simpleCalculator.cpp)[simpleCalculator.cpp]
-division function would be added to (https://github.com/karastoyanov/linux-hobby-club/blob/development/CPP/simpleCalculator.cpp)[simpleCalculator.cpp]

**Comment by karastoyanov** [comment]
- multiple function would be added to (simpleCalculator.cpp)[https://github.com/karastoyanov/linux-hobby-club/blob/development/CPP/simpleCalculator.cpp]
 - division function would be added to (simpleCalculator.cpp)[https://github.com/karastoyanov/linux-hobby-club/blob/development/CPP/simpleCalculator.cpp]

**Comment by karastoyanov** [comment]
Issue resolved with commit [aa4132c](https://github.com/karastoyanov/linux-hobby-club/commit/aa4132c36e7857f763c613dfae7949befba1953a):
 - Multiple functionality added
 - Divison functionality added
 - Additional COUT's added
